version: '3.9'

services:
  shard1:
    image: mongo:6.0
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27018"]
    ports:
      - 27018:27018
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:6.0
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27020"]
    ports:
      - 27020:27020
    volumes:
      - shard2_data:/data/db

  configsvr:
    image: mongo:6.0
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "cfg", "--port", "27019"]
    ports:
      - 27019:27019
    volumes:
      - configsvr_data:/data/db

  mongos:
    image: mongo:6.0
    container_name: mongos
    depends_on:
      - shard1
      - shard2
      - configsvr
    command: ["mongos", "--configdb", "cfg/configsvr:27019", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27021:27017

volumes:
  shard1_data:
  shard2_data:
  configsvr_data:
