services:
  mongo:
    image: mongo:6.0
    container_name: shard_mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ../backend
    container_name: shard_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/ticketing
      - PORT=3000
    volumes:
      - ../backend:/app
    depends_on:
      - mongo
